config/routes.rb
Rails.application.routes.draw do
  root "locations#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :locations, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:edit, :update, :destroy]

  def index
    @locations = Current.user.locations.includes(:user)
    @forecasts = fetch_forecasts_for_locations(@locations)
    @new_location = Location.new
  end

  def new
    @location = Location.new
  end

  def show
    @location = Location.find(params[:location_id])
    service = OpenMeteoService.new(@location.latitude, @location.longitude)
    response = service.fetch_forecast

    if response && response["daily"]
      @forecast = response["daily"]
    else
      @forecast = nil
      flash[:alert] = "Unable to fetch forecast data. Please try again later."
    end
  end

  def create
    address = params[:address]
    title = params[:title]
    if address.blank? || title.blank?
      flash[:alert] = address.blank? ? "Address or IP cannot be blank." : "Title cannot be blank."
      redirect_to locations_path and return
    end

    location_data = fetch_location_data(address)
    if location_data
      @location = Current.user.locations.find_by(
        title: title,
        latitude: location_data[:latitude],
        longitude: location_data[:longitude]
      ) || Current.user.locations.create(location_data.merge!(title: title))
      redirect_to location_path(@location)
    else
      flash[:alert] = "Unable to find the entered location."
      redirect_to locations_path
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      flash[:notice] = "Location title updated successfully."
      redirect_to locations_path
    else
      flash[:alert] = "Failed to update the location title."
      render :edit
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private

  def is_ip?(user_input)
    user_input =~ Resolv::IPv4::Regex || user_input =~ Resolv::IPv6::Regex
  end

  def fetch_location_data(user_input)
    service = is_ip?(user_input) ? IpapiService.new(user_input) : GeocodeService.new(user_input)
    service.fetch_location
  end

  def fetch_forecasts_for_locations(locations)
    locations.each_with_object({}) do |location, forecasts|
      service = OpenMeteoService.new(location.latitude, location.longitude)
      forecasts[location.id] = service.fetch_forecast
    end
  end

  def set_location
    @location = Current.user.locations.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:title)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for(@user)
      redirect_to root_path, notice: "Account created successfully."
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
    rescue ActiveRecord::RecordNotUnique
      flash[:alert] = "This email is already registered."
      redirect_to new_user_path
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weather Forecasting Application" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <% if Current.user %>
        Logged in as <%= Current.user.email_address %> |
        <%= link_to "Logout", session_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "Login", new_session_path %> |
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/locations/_location.html.erb
<div>
  <h2><%= location.title %></h2>
  <table class="forecast-table">
    <thead>
    <tr>
      <% forecast[:dates].each do |date| %>
        <th><%= Date.parse(date).strftime("%b %d") %></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <tr>
      <% forecast[:highs].each do |high| %>
        <td><%= high %>°F</td>
      <% end %>
    </tr>
    <tr>
      <% forecast[:lows].each do |low| %>
        <td><%= low %>°F</td>
      <% end %>
    </tr>
    </tbody>
  </table>
  <img src="<%= forecast[:chart_url] %>" alt="Weather Forecast Graph" />
  <%= button_to "Edit", edit_location_path(location), method: :get %>
  <%= form_with model: location, url: location_path(location), method: :delete, local: true do %>
    <%= submit_tag "Delete" %>
  <% end %>
</div>

app/views/locations/edit.html.erb
<h1>Edit Location Title</h1>

<%= form_with model: @location, local: true do |form| %>
  <div>
    <%= form.label :title, "Location Title" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.submit "Update Title" %>
    <%= button_to "Cancel", locations_path %>
  </div>
<% end %>

app/views/locations/index.html.erb
<h2>Add a Location</h2>

<% if flash[:alert] %>
  <div style="color: red; margin-bottom: 1rem;">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= form_with url: locations_path, method: :post, local: true do |form| %>
  <div>
    <%= form.label :title, "Title" %>
    <%= form.text_field :title, size: 40 %>
  </div>
  <div>
    <%= form.label :address, "Enter Street Address, Zipcode, or IP Address" %>
    <%= form.text_field :address, placeholder: "street city state zipcode, or zipcode, or x.x.x.x", size: 40 %>
  </div>
  <%= form.submit "Get Forecast" %>
<% end %>

<h1>Your Locations and Forecasts</h1>
<% if @locations.any? %>
  <% @locations.each do |location| %>
    <% if @forecasts[location.id] %>
      <%= render "locations/location", location: location, forecast: @forecasts[location.id] %>
    <% else %>
      <p>Unable to retrieve forecast data for this location.</p>
    <% end %>
  <% end %>
<% else %>
  <p>No locations found.</p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>
<%= form_with model: @user, url: users_path, method: :post, local: true do |form| %>
  <div>
    <%= form.label :email_address, "Email Address" %>
    <%= form.email_field :email_address, required: true, autofocus: true %>
  </div>
  <br>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, required: true %>
  </div>
  <br>
  <div>
    <%= form.label :password_confirmation, "Confirm Password" %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>
  <br>
  <%= form.submit "Sign Up" %>
<% end %>